### ISSUE TITLE
Enable HTTPS on Netlify once DNS resolves

### ISSUE THREAD

**Issue by tmcw** [tmcw/geojson.net#1]
Will fix

- https://github.com/mapbox/geojson.io/issues/620
- https://github.com/mapbox/geojson.io/issues/607
- https://github.com/mapbox/geojson.io/issues/596

**Comment by tmcw** [comment]
Done.

**Comment by develar** [comment]
geojson.net GitHub auth is broken also :(

**Comment by tmcw** [comment]
See https://github.com/tmcw/geojson.net/issues/18 - please note the _not a product or company_ bit in the readme - my work on geojson.net is in my free time, and if you desperately need a feature, the way to get it is to help and implement it.

**Comment by vgensini** [comment]
Because the auth for GitHub is broken, I'm unable to share any maps. Is there a fix that anyone knows of?

**Comment by tmcw** [comment]
Locking; refer to #18: GitHub auth is a work in progress. If you need it, please help implement it.
