### ISSUE TITLE
Compact prettified json

### ISSUE THREAD

**Issue by bhousel** [tmcw/geojson.net#10]
Any objection if I switch the stringify code [here](https://github.com/tmcw/geojson.net/blob/dfe0499248202870fa39b7fcd1c71803f9dc41a9/src/panel/json.js#L106) to use
https://github.com/lydell/json-stringify-pretty-compact ? 

It's much nicer to look at and the resulting geojsons diff better.

**Comment by tmcw** [comment]
Yep! Seems cool to me.
