### ISSUE TITLE
Hash

### ISSUE THREAD

**Issue by tmcw** [tmcw/geojson.net#22]

**Comment by bhousel** [comment]
Ooh can you say more? This sounds like something I’ve wanted, if you mean some kind of unique id generation. 

I was considering writing a thing to md5 (or something) the `geometry` and `properties` and stick that into the `id` property.

**Comment by tmcw** [comment]
This is just for recreating the hash that keeps the map in the same place for when you reload. Still very much in the 'making it work' phase, anything in addition to previous functionality is tagged pony.

**Comment by bhousel** [comment]
Ahh yeah that makes more sense, thanks!
(The thing I was saying should really be a separate library anyway)
