### ISSUE TITLE
GeoJSON file import failing

### ISSUE THREAD

**Issue by danburzo** [tmcw/geojson.net#39]
Hi Tom,

Importing a GeoJSON file from <kbd>Open > File</kbd> fails here:

https://github.com/tmcw/geojson.net/blob/c0375f963b95e41f1b4916ae90e3c628a483adeb/src/ui/file_bar.js#L28-L41

...since `geojsons` are Promises and `mergeGeojson` doesn't seem to handle those.

Should it wait for the file contents to be available? Something like:

```js
const geojsons = await Promise.all( ... )
```

**Comment by tmcw** [comment]
Yep, I think that's the issue.

**Comment by danburzo** [comment]
Cool! If that's an okay solution, I can submit a PR.

**Comment by tmcw** [comment]
Sure, I'd accept that PR.
