### ISSUE TITLE
Latitude and Longitude are incorrect on Marker

### ISSUE THREAD

**Issue by lostpebble** [tmcw/geojson.net#44]
Just noticed that when looking under "Statistics' on a marker, the latitude and longitude values are switched.

GeoJson going against the regular standard of (LAT,LNG) is the probable cause... Still not completely sure why they felt the need to switch them and go against the grain.

**Comment by tmcw** [comment]
🤔 Nope. [Nope.](https://macwright.org/lonlat). [Nope](https://macwright.org/2016/07/15/longitude-latitude-is-the-right-way.html).

**Comment by lostpebble** [comment]
The issue still stands... They are pointing to the wrong values. I'm just stating that you might have mixed it up because of the non-agreement of standards when it comes to the order.

For example, I place a marker in Johannesburg, South Africa and click on the marker, go to "statistics" and the reading is:

```
Latitude 28.0479
Longitude -26.1981
```

When this point is actually at _Longitude_ 28.0479, and _Latitude_ -26.1981.
