### ISSUE TITLE
Necessity of zeit.co/now

### ISSUE THREAD

**Issue by chazanov** [tmcw/geojson.net#50]
Hi Tom,

for what do I exactly need the zeit.co/now dependency? As I am a non-American patriot it's illegal for me to use AWS.

Source: https://github.com/tmcw/geojson.net/pull/47

**Comment by tmcw** [comment]
A server component is necessary to authenticate against GitHub. Not sure whether you mean use AWS as in use services that use AWS (if in that case, I must warn you, chances are that GitHub uses AWS too). If the question is deploying, well - it should be possible to deploy on another service, but it'll be up to you to figure out the deployment strategy.
