### ISSUE TITLE
On which port is geojson.net served?

### ISSUE THREAD

**Issue by baerbock** [tmcw/geojson.net#51]
http://localhost:1234/ seems to be just the API:
`Cannot GET /`

But on which port is the webpage getting served?

**Comment by jgimbel** [comment]
Set `NODE_ENV=dev` to start the Dev server

**Comment by baerbock** [comment]
@jgimbel Sorry for delay, I've just had meal ;)
yarn is trying to install babel-core two times, so setup fails:

`warning Pattern ["babel-core@^6.26.3"] is trying to unpack in the same destination "./.cache/yarn/v4/npm-babel-core-6.26.3-b2e2f09e342d0f0c88e2f02e067794125e75c207/node_modules/babel-core" as pattern ["babel-core@^6.25.0","babel-core@^6.26.0","babel-core@^6.0.0","babel-core@^6.0.0"]. This could result in non-deterministic behavior, skipping.`

I've just wanted to fix this, but what exactly is wrong in package.json ?

**Comment by jgimbel** [comment]
I believe this is something that caused by yarn. It is trying to cache a version of babel-core for you, so you don't keep downloading it on every install. Here it is warning that it is caching version 6.26.3 for babel-core version 6.25 and 6.26, and all 6.*.* versions. If it isn't causing an error, I would not worry about it, chances are 6.26.3 will work for all versions of babel-core that you need.

**Comment by baerbock** [comment]
Thanks for your help, everything up now.

One last thing: I've tried to adapt [geojsonio.sh](https://gist.github.com/ajashton/6504728)

But my localhost geojson.net just doesn't display any data: Does [this localhost link](http://localhost:1234/#data=data:application/json,%7B%0A%20%20%22type%22%3A%20%22FeatureCollection%22%2C%0A%20%20%22features%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22type%22%3A%20%22Feature%22%2C%0A%20%20%20%20%20%20%22id%22%3A%20%22relation%2F3895376%22%2C%0A%20%20%20%20%20%20%22properties%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22name%22%3A%20%22%D0%96%D0%9F%20%D0%9B%D0%B8%D0%BD%D0%B8%D1%8F%2019%20%D0%9A%D1%80%D1%83%D0%BC%D0%BE%D0%B2%D0%BE%20-%20%D0%90%D1%81%D0%B5%D0%BD%D0%BE%D0%B2%D0%B3%D1%80%D0%B0%D0%B4%22%2C%0A%20%20%20%20%20%20%20%20%22ref%22%3A%20%2219%22%2C%0A%20%20%20%20%20%20%20%20%22route%22%3A%20%22railway%22%2C%0A%20%20%20%20%20%20%20%20%22type%22%3A%20%22route%22%2C%0A%20%20%20%20%20%20%20%20%22id%22%3A%20%22relation%2F3895376%22%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%22geometry%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22type%22%3A%20%22LineString%22%2C%0A%20%20%20%20%20%20%20%20%22coordinates%22%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%2024.8168783%2C%0A%20%20%20%20%20%20%20%20%20%20%20%2042.0934742%0A%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%2024.8735781%2C%0A%20%20%20%20%20%20%20%20%20%20%20%2042.0124526%0A%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D%0A) work for you?

**Comment by jgimbel** [comment]
I don't believe that functionality is included in geojson.net. 
Unfortunately, I don't have a lot of experience with geojson.net yet, and I am not sure geojson.net has a  way to post data like geojson.io did.

@tmcw Any thoughts on if/how we can support a command line api anymore?

**Comment by tmcw** [comment]
This is pretty much the same as #45, which I closed by removing API.md. geojson.net isn't compatible with the URL API of geojson.io at this point - it's potentially a goal in the future. The CLI constructed a URL that's compatible with geojson.io but not .net.

**Comment by oofpez** [comment]
I got the same error and Set `NODE_ENV=dev` to start the Dev serve

but now, if I just go to localhost:1234, There's only a white screen and I get this error:

Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at Function.create (<anonymous>)
    at Object.inherits (inherits_browser.js:5)
    at Object.parcelRequire.node_modules/readable-stream/lib/_stream_writable.js.process-nextick-args (_stream_writable.js:96)
    at newRequire (src.a2b27638.js:49)
    at localRequire (src.a2b27638.js:55)
    at Object.parcelRequire.node_modules/readable-stream/writable-browser.js../lib/_stream_writable.js (writable-browser.js:1)
    at newRequire (src.a2b27638.js:49)
    at localRequire (src.a2b27638.js:55)
    at Object.parcelRequire.node_modules/stream-browserify/index.js.events (index.js:29)
    at newRequire (src.a2b27638.js:49)
