### ISSUE TITLE
enable gist by url querystring

### ISSUE THREAD

**Issue by mikofski** [tmcw/geojson.net#59]
Hi Tim, thank you very much for [geojson.net](https://geojson.net/) and [geojson.io](http://geojson.io/)! I really like these tools a lot, but like others I have concerns with the permissions. OK, call me paranoid ;) One idea would be to make it like this [nbviewer](https://nbviewer.jupyter.org/) where when sharing or getting data from pubic gists and repos, you only have to provide the URL. Since the data is public anyway, an oauth token might not even be necessary. Anyway, just an idea, feel free to close this as I probably won't send a PR, sorry.

related issues:
* https://github.com/mapbox/geojson.io/issues/506
* https://github.com/mapbox/geojson.io/issues/608
* #8 
* #2 

probably more

**Comment by tmcw** [comment]
Hi there - if you'd like to solve the long-discussed security-or-ease issue, open a PR solving it, please.
