### ISSUE TITLE
Migrate off of Mapbox Classic Style implementation

### ISSUE THREAD

**Issue by riastrad** [tmcw/geojson.net#61]
Currently this app uses the Mapbox Legacy Maps API & a default classic style (`mapbox.streets`) for it's primary `tileLayer`:

https://github.com/tmcw/geojson.net/blob/71bbccbbe1f2a87eb6aa5ec4531e41f5c93dd665/src/layers.js#L9

Support for Classic Styles is slated to end on June 1, 2020: https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4.

Because this implementation uses a Mapbox template style, migrating to the new endpoints should be fairly straightforward: https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/#leaflet-implementations

**Comment by tmcw** [comment]
Happy to accept a PR with any changes!

**Comment by gregmihalko** [comment]
This actually still doesn't work. We've swapped in our own mapbox key and style with no luck. Errors I get no matter what are 404 (not found)

**Comment by riastrad** [comment]
@gregmihalko this isn't really a great location to troubleshoot why you might be getting 404s in your own implementation. I would encourage you to send in your issue with as much detail as possible to the Mapbox Support team: https://support.mapbox.com/hc/en-us.

**Comment by gregmihalko** [comment]
@riastrad It's not just in my own implementation, these updates, updated key and changes to the api.mapbox vs b.tiles doesn't work.

**Comment by gregmihalko** [comment]
@riastrad @tmcw any thoughts as to why the mapbox updates here are throwing an error?
